import re
import ast

id_to_names = {}

for line in open('winuser.h'):
    line = line.rstrip()
    m = re.match(r'#define\s+(WM_\w+)\s+(.*)', line)
    if not m:
        continue
    name = m.group(1)
    id = m.group(2)
    try:
        id = ast.literal_eval(id)
    except (SyntaxError, ValueError) as e:
        print(e, repr(line))
        continue

    if name in ('WM_KEYFIRST', 'WM_KEYLAST', 'WM_MOUSEFIRST', 'WM_MOUSELAST', 'WM_IME_KEYLAST'):
        continue

    id_to_names.setdefault(id, []).append(name)

for k, v in id_to_names.items():
    assert len(v) == 1, (k, v)

print()
print('// generated by extract.py')
print('const ID_TO_NAME: &[(u32, &str)] = &[')
for k, [v] in sorted(id_to_names.items()):
    print(f'    (0x{k:04x}, "{v}"),')
print('];')
